// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.UIManager UIManager;
    
    private Gtk.Action FileAction;
    
    private Gtk.Action HelpAction;
    
    private Gtk.Action exitAction;
    
    private Gtk.VBox vbox2;
    
    private Gtk.MenuBar menubar1;
    
    private Gtk.HBox hbox4;
    
    private Gtk.Notebook notebook1;
    
    private Gtk.VBox vbox5;
    
    private Gtk.HBox hbox1;
    
    private Gtk.Image image3;
    
    private Gtk.Label label31;
    
    private Gtk.HBox hbox8;
    
    private Gtk.Label label14;
    
    private Gtk.Label label17;
    
    private Gtk.Label label15;
    
    private Gtk.Label label16;
    
    private Gtk.HBox hbox7;
    
    private Gtk.HSeparator hseparator3;
    
    private Gtk.HBox hbox9;
    
    private Gtk.Label label18;
    
    private Gtk.Label label21;
    
    private Gtk.Label label19;
    
    private Gtk.Label label20;
    
    private Gtk.HBox hbox3;
    
    private Gtk.Label label22;
    
    private Gtk.Label label25;
    
    private Gtk.Label label24;
    
    private Gtk.Label label23;
    
    private Gtk.HBox hbox21;
    
    private Gtk.Label label26;
    
    private Gtk.Label label29;
    
    private Gtk.Label label28;
    
    private Gtk.Label label27;
    
    private Gtk.HBox hbox22;
    
    private Gtk.HSeparator hseparator4;
    
    private Gtk.Label label1;
    
    private Gtk.VBox vbox3;
    
    private Gtk.HBox hbox5;
    
    private Gtk.Image image1;
    
    private Gtk.Label label2;
    
    private Gtk.VBox vbox4;
    
    private Gtk.HBox hbox6;
    
    private Gtk.Image image2;
    
    private Gtk.Label label3;
    
    private Gtk.VBox vbox6;
    
    private Gtk.HBox hbox10;
    
    private Gtk.Label label10;
    
    private Gtk.HBox hbox19;
    
    private Gtk.HSeparator hseparator2;
    
    private Gtk.HBox hbox11;
    
    private Gtk.Label label5;
    
    private Gtk.Entry entry1;
    
    private Gtk.HBox hbox12;
    
    private Gtk.Label label6;
    
    private Gtk.Entry entry2;
    
    private Gtk.HBox hbox13;
    
    private Gtk.Label label7;
    
    private Gtk.Entry entry3;
    
    private Gtk.HBox hbox14;
    
    private Gtk.Label label8;
    
    private Gtk.Entry entry4;
    
    private Gtk.Label label30;
    
    private Gtk.HBox hbox20;
    
    private Gtk.Label label11;
    
    private Gtk.HBox hbox18;
    
    private Gtk.HSeparator hseparator1;
    
    private Gtk.HBox hbox15;
    
    private Gtk.Label label9;
    
    private Gtk.ComboBox combobox1;
    
    private Gtk.HBox hbox16;
    
    private Gtk.Label label12;
    
    private Gtk.ComboBox combobox4;
    
    private Gtk.HBox hbox17;
    
    private Gtk.Label label13;
    
    private Gtk.ComboBox combobox3;
    
    private Gtk.HBox hbox23;
    
    private Gtk.HSeparator hseparator5;
    
    private Gtk.HBox hbox24;
    
    private Gtk.Button button1;
    
    private Gtk.Label label4;
    
    private Gtk.Statusbar statusbar1;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.UIManager = new Gtk.UIManager();
        Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
        this.FileAction = new Gtk.Action("FileAction", Mono.Unix.Catalog.GetString("File"), null, null);
        this.FileAction.ShortLabel = Mono.Unix.Catalog.GetString("File");
        w1.Add(this.FileAction, null);
        this.HelpAction = new Gtk.Action("HelpAction", Mono.Unix.Catalog.GetString("Help"), null, null);
        this.HelpAction.ShortLabel = Mono.Unix.Catalog.GetString("Help");
        w1.Add(this.HelpAction, null);
        this.exitAction = new Gtk.Action("exitAction", Mono.Unix.Catalog.GetString("exit"), null, null);
        this.exitAction.ShortLabel = Mono.Unix.Catalog.GetString("exit");
        w1.Add(this.exitAction, null);
        this.UIManager.InsertActionGroup(w1, 0);
        this.AddAccelGroup(this.UIManager.AccelGroup);
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("Smart Broadband Usage Viewer");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        this.SkipPagerHint = true;
        this.SkipTaskbarHint = true;
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox2 = new Gtk.VBox();
        this.vbox2.Name = "vbox2";
        this.vbox2.Spacing = 6;
        // Container child vbox2.Gtk.Box+BoxChild
        this.UIManager.AddUiFromString("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='exitAction' action='exitAction'/></menu><menu name='HelpAction' action='HelpAction'/></menubar></ui>");
        this.menubar1 = ((Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
        this.menubar1.Name = "menubar1";
        this.vbox2.Add(this.menubar1);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox2[this.menubar1]));
        w2.Position = 0;
        w2.Expand = false;
        w2.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.hbox4 = new Gtk.HBox();
        this.hbox4.Name = "hbox4";
        this.hbox4.Spacing = 6;
        // Container child hbox4.Gtk.Box+BoxChild
        this.notebook1 = new Gtk.Notebook();
        this.notebook1.CanFocus = true;
        this.notebook1.Name = "notebook1";
        this.notebook1.CurrentPage = 0;
        this.notebook1.Scrollable = true;
        // Container child notebook1.Gtk.Notebook+NotebookChild
        this.vbox5 = new Gtk.VBox();
        this.vbox5.Name = "vbox5";
        this.vbox5.Spacing = 6;
        // Container child vbox5.Gtk.Box+BoxChild
        this.hbox1 = new Gtk.HBox();
        this.hbox1.Name = "hbox1";
        this.hbox1.Spacing = 6;
        // Container child hbox1.Gtk.Box+BoxChild
        this.image3 = new Gtk.Image();
        this.image3.Name = "image3";
        this.hbox1.Add(this.image3);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox1[this.image3]));
        w3.Position = 0;
        w3.Expand = false;
        w3.Fill = false;
        w3.Padding = ((uint)(25));
        // Container child hbox1.Gtk.Box+BoxChild
        this.label31 = new Gtk.Label();
        this.label31.Name = "label31";
        this.label31.LabelProp = Mono.Unix.Catalog.GetString("This application is not produced by smart telecom, and the writer / provider is no way affiliated with smart telcom, use at your own peril.");
        this.label31.Wrap = true;
        this.hbox1.Add(this.label31);
        Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox1[this.label31]));
        w4.Position = 1;
        w4.Expand = false;
        w4.Fill = false;
        this.vbox5.Add(this.hbox1);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox5[this.hbox1]));
        w5.Position = 0;
        w5.Expand = false;
        w5.Fill = false;
        w5.Padding = ((uint)(20));
        // Container child vbox5.Gtk.Box+BoxChild
        this.hbox8 = new Gtk.HBox();
        this.hbox8.Name = "hbox8";
        this.hbox8.Spacing = 6;
        // Container child hbox8.Gtk.Box+BoxChild
        this.label14 = new Gtk.Label();
        this.label14.WidthRequest = 120;
        this.label14.Name = "label14";
        this.label14.LabelProp = Mono.Unix.Catalog.GetString("Summary");
        this.hbox8.Add(this.label14);
        Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox8[this.label14]));
        w6.Position = 0;
        w6.Fill = false;
        w6.Padding = ((uint)(6));
        // Container child hbox8.Gtk.Box+BoxChild
        this.label17 = new Gtk.Label();
        this.label17.WidthRequest = 120;
        this.label17.Name = "label17";
        this.label17.LabelProp = Mono.Unix.Catalog.GetString("Today MB(Gb)");
        this.hbox8.Add(this.label17);
        Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox8[this.label17]));
        w7.Position = 1;
        w7.Fill = false;
        w7.Padding = ((uint)(6));
        // Container child hbox8.Gtk.Box+BoxChild
        this.label15 = new Gtk.Label();
        this.label15.WidthRequest = 120;
        this.label15.Name = "label15";
        this.label15.LabelProp = Mono.Unix.Catalog.GetString("Last 7 Days MB (Gb)");
        this.hbox8.Add(this.label15);
        Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox8[this.label15]));
        w8.Position = 2;
        w8.Fill = false;
        w8.Padding = ((uint)(6));
        // Container child hbox8.Gtk.Box+BoxChild
        this.label16 = new Gtk.Label();
        this.label16.WidthRequest = 120;
        this.label16.Name = "label16";
        this.label16.LabelProp = Mono.Unix.Catalog.GetString("Last 30 Days MB (Gb)");
        this.hbox8.Add(this.label16);
        Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.hbox8[this.label16]));
        w9.Position = 3;
        w9.Fill = false;
        w9.Padding = ((uint)(6));
        this.vbox5.Add(this.hbox8);
        Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox5[this.hbox8]));
        w10.Position = 1;
        w10.Expand = false;
        w10.Fill = false;
        w10.Padding = ((uint)(6));
        // Container child vbox5.Gtk.Box+BoxChild
        this.hbox7 = new Gtk.HBox();
        this.hbox7.Name = "hbox7";
        this.hbox7.Spacing = 6;
        // Container child hbox7.Gtk.Box+BoxChild
        this.hseparator3 = new Gtk.HSeparator();
        this.hseparator3.Name = "hseparator3";
        this.hbox7.Add(this.hseparator3);
        Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox7[this.hseparator3]));
        w11.Position = 0;
        w11.Padding = ((uint)(6));
        this.vbox5.Add(this.hbox7);
        Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.vbox5[this.hbox7]));
        w12.Position = 2;
        w12.Expand = false;
        w12.Fill = false;
        // Container child vbox5.Gtk.Box+BoxChild
        this.hbox9 = new Gtk.HBox();
        this.hbox9.Name = "hbox9";
        this.hbox9.Spacing = 6;
        // Container child hbox9.Gtk.Box+BoxChild
        this.label18 = new Gtk.Label();
        this.label18.WidthRequest = 120;
        this.label18.Name = "label18";
        this.label18.LabelProp = Mono.Unix.Catalog.GetString("Downstream");
        this.hbox9.Add(this.label18);
        Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.hbox9[this.label18]));
        w13.Position = 0;
        w13.Fill = false;
        w13.Padding = ((uint)(6));
        // Container child hbox9.Gtk.Box+BoxChild
        this.label21 = new Gtk.Label();
        this.label21.WidthRequest = 120;
        this.label21.Name = "label21";
        this.label21.LabelProp = Mono.Unix.Catalog.GetString("label5");
        this.hbox9.Add(this.label21);
        Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.hbox9[this.label21]));
        w14.Position = 1;
        w14.Fill = false;
        w14.Padding = ((uint)(6));
        // Container child hbox9.Gtk.Box+BoxChild
        this.label19 = new Gtk.Label();
        this.label19.WidthRequest = 120;
        this.label19.Name = "label19";
        this.label19.LabelProp = Mono.Unix.Catalog.GetString("label6");
        this.hbox9.Add(this.label19);
        Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.hbox9[this.label19]));
        w15.Position = 2;
        w15.Fill = false;
        w15.Padding = ((uint)(6));
        // Container child hbox9.Gtk.Box+BoxChild
        this.label20 = new Gtk.Label();
        this.label20.WidthRequest = 120;
        this.label20.Name = "label20";
        this.label20.LabelProp = Mono.Unix.Catalog.GetString("label7");
        this.hbox9.Add(this.label20);
        Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.hbox9[this.label20]));
        w16.Position = 3;
        w16.Fill = false;
        w16.Padding = ((uint)(6));
        this.vbox5.Add(this.hbox9);
        Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.vbox5[this.hbox9]));
        w17.Position = 3;
        w17.Expand = false;
        w17.Fill = false;
        w17.Padding = ((uint)(6));
        // Container child vbox5.Gtk.Box+BoxChild
        this.hbox3 = new Gtk.HBox();
        this.hbox3.Name = "hbox3";
        this.hbox3.Spacing = 6;
        // Container child hbox3.Gtk.Box+BoxChild
        this.label22 = new Gtk.Label();
        this.label22.WidthRequest = 120;
        this.label22.Name = "label22";
        this.label22.LabelProp = Mono.Unix.Catalog.GetString("Upstream");
        this.hbox3.Add(this.label22);
        Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.hbox3[this.label22]));
        w18.Position = 0;
        w18.Fill = false;
        w18.Padding = ((uint)(6));
        // Container child hbox3.Gtk.Box+BoxChild
        this.label25 = new Gtk.Label();
        this.label25.WidthRequest = 120;
        this.label25.Name = "label25";
        this.label25.LabelProp = Mono.Unix.Catalog.GetString("label11");
        this.hbox3.Add(this.label25);
        Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(this.hbox3[this.label25]));
        w19.Position = 1;
        w19.Fill = false;
        w19.Padding = ((uint)(6));
        // Container child hbox3.Gtk.Box+BoxChild
        this.label24 = new Gtk.Label();
        this.label24.WidthRequest = 120;
        this.label24.Name = "label24";
        this.label24.LabelProp = Mono.Unix.Catalog.GetString("label10");
        this.hbox3.Add(this.label24);
        Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(this.hbox3[this.label24]));
        w20.Position = 2;
        w20.Fill = false;
        w20.Padding = ((uint)(6));
        // Container child hbox3.Gtk.Box+BoxChild
        this.label23 = new Gtk.Label();
        this.label23.WidthRequest = 120;
        this.label23.Name = "label23";
        this.label23.LabelProp = Mono.Unix.Catalog.GetString("label9");
        this.hbox3.Add(this.label23);
        Gtk.Box.BoxChild w21 = ((Gtk.Box.BoxChild)(this.hbox3[this.label23]));
        w21.Position = 3;
        w21.Fill = false;
        w21.Padding = ((uint)(6));
        this.vbox5.Add(this.hbox3);
        Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(this.vbox5[this.hbox3]));
        w22.Position = 4;
        w22.Expand = false;
        w22.Fill = false;
        w22.Padding = ((uint)(6));
        // Container child vbox5.Gtk.Box+BoxChild
        this.hbox21 = new Gtk.HBox();
        this.hbox21.Name = "hbox21";
        this.hbox21.Spacing = 6;
        // Container child hbox21.Gtk.Box+BoxChild
        this.label26 = new Gtk.Label();
        this.label26.WidthRequest = 120;
        this.label26.Name = "label26";
        this.label26.LabelProp = Mono.Unix.Catalog.GetString("Total");
        this.hbox21.Add(this.label26);
        Gtk.Box.BoxChild w23 = ((Gtk.Box.BoxChild)(this.hbox21[this.label26]));
        w23.Position = 0;
        w23.Fill = false;
        w23.Padding = ((uint)(6));
        // Container child hbox21.Gtk.Box+BoxChild
        this.label29 = new Gtk.Label();
        this.label29.WidthRequest = 120;
        this.label29.Name = "label29";
        this.label29.LabelProp = Mono.Unix.Catalog.GetString("label15");
        this.hbox21.Add(this.label29);
        Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(this.hbox21[this.label29]));
        w24.Position = 1;
        w24.Fill = false;
        w24.Padding = ((uint)(6));
        // Container child hbox21.Gtk.Box+BoxChild
        this.label28 = new Gtk.Label();
        this.label28.WidthRequest = 120;
        this.label28.Name = "label28";
        this.label28.LabelProp = Mono.Unix.Catalog.GetString("label14");
        this.hbox21.Add(this.label28);
        Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(this.hbox21[this.label28]));
        w25.Position = 2;
        w25.Fill = false;
        w25.Padding = ((uint)(6));
        // Container child hbox21.Gtk.Box+BoxChild
        this.label27 = new Gtk.Label();
        this.label27.WidthRequest = 120;
        this.label27.Name = "label27";
        this.label27.LabelProp = Mono.Unix.Catalog.GetString("label13");
        this.hbox21.Add(this.label27);
        Gtk.Box.BoxChild w26 = ((Gtk.Box.BoxChild)(this.hbox21[this.label27]));
        w26.Position = 3;
        w26.Fill = false;
        w26.Padding = ((uint)(6));
        this.vbox5.Add(this.hbox21);
        Gtk.Box.BoxChild w27 = ((Gtk.Box.BoxChild)(this.vbox5[this.hbox21]));
        w27.Position = 5;
        w27.Expand = false;
        w27.Fill = false;
        w27.Padding = ((uint)(6));
        // Container child vbox5.Gtk.Box+BoxChild
        this.hbox22 = new Gtk.HBox();
        this.hbox22.Name = "hbox22";
        this.hbox22.Spacing = 6;
        // Container child hbox22.Gtk.Box+BoxChild
        this.hseparator4 = new Gtk.HSeparator();
        this.hseparator4.Name = "hseparator4";
        this.hbox22.Add(this.hseparator4);
        Gtk.Box.BoxChild w28 = ((Gtk.Box.BoxChild)(this.hbox22[this.hseparator4]));
        w28.Position = 0;
        w28.Padding = ((uint)(6));
        this.vbox5.Add(this.hbox22);
        Gtk.Box.BoxChild w29 = ((Gtk.Box.BoxChild)(this.vbox5[this.hbox22]));
        w29.Position = 6;
        w29.Expand = false;
        w29.Fill = false;
        this.notebook1.Add(this.vbox5);
        // Notebook tab
        this.label1 = new Gtk.Label();
        this.label1.Name = "label1";
        this.label1.LabelProp = Mono.Unix.Catalog.GetString("Summary");
        this.notebook1.SetTabLabel(this.vbox5, this.label1);
        this.label1.ShowAll();
        // Container child notebook1.Gtk.Notebook+NotebookChild
        this.vbox3 = new Gtk.VBox();
        this.vbox3.Name = "vbox3";
        this.vbox3.Spacing = 6;
        // Container child vbox3.Gtk.Box+BoxChild
        this.hbox5 = new Gtk.HBox();
        this.hbox5.Name = "hbox5";
        this.hbox5.Spacing = 6;
        // Container child hbox5.Gtk.Box+BoxChild
        this.image1 = new Gtk.Image();
        this.image1.Name = "image1";
        this.hbox5.Add(this.image1);
        Gtk.Box.BoxChild w31 = ((Gtk.Box.BoxChild)(this.hbox5[this.image1]));
        w31.Position = 1;
        w31.Expand = false;
        w31.Fill = false;
        this.vbox3.Add(this.hbox5);
        Gtk.Box.BoxChild w32 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbox5]));
        w32.Position = 1;
        w32.Expand = false;
        w32.Fill = false;
        this.notebook1.Add(this.vbox3);
        Gtk.Notebook.NotebookChild w33 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox3]));
        w33.Position = 1;
        // Notebook tab
        this.label2 = new Gtk.Label();
        this.label2.Name = "label2";
        this.label2.LabelProp = Mono.Unix.Catalog.GetString("Daily");
        this.notebook1.SetTabLabel(this.vbox3, this.label2);
        this.label2.ShowAll();
        // Container child notebook1.Gtk.Notebook+NotebookChild
        this.vbox4 = new Gtk.VBox();
        this.vbox4.Name = "vbox4";
        this.vbox4.Spacing = 6;
        // Container child vbox4.Gtk.Box+BoxChild
        this.hbox6 = new Gtk.HBox();
        this.hbox6.Name = "hbox6";
        this.hbox6.Spacing = 6;
        // Container child hbox6.Gtk.Box+BoxChild
        this.image2 = new Gtk.Image();
        this.image2.Name = "image2";
        this.hbox6.Add(this.image2);
        Gtk.Box.BoxChild w34 = ((Gtk.Box.BoxChild)(this.hbox6[this.image2]));
        w34.Position = 1;
        w34.Expand = false;
        w34.Fill = false;
        this.vbox4.Add(this.hbox6);
        Gtk.Box.BoxChild w35 = ((Gtk.Box.BoxChild)(this.vbox4[this.hbox6]));
        w35.Position = 1;
        w35.Expand = false;
        w35.Fill = false;
        this.notebook1.Add(this.vbox4);
        Gtk.Notebook.NotebookChild w36 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox4]));
        w36.Position = 2;
        // Notebook tab
        this.label3 = new Gtk.Label();
        this.label3.Name = "label3";
        this.label3.LabelProp = Mono.Unix.Catalog.GetString("Cumulative");
        this.notebook1.SetTabLabel(this.vbox4, this.label3);
        this.label3.ShowAll();
        // Container child notebook1.Gtk.Notebook+NotebookChild
        this.vbox6 = new Gtk.VBox();
        this.vbox6.Name = "vbox6";
        this.vbox6.Spacing = 6;
        // Container child vbox6.Gtk.Box+BoxChild
        this.hbox10 = new Gtk.HBox();
        this.hbox10.Name = "hbox10";
        this.hbox10.Spacing = 6;
        // Container child hbox10.Gtk.Box+BoxChild
        this.label10 = new Gtk.Label();
        this.label10.Name = "label10";
        this.label10.LabelProp = Mono.Unix.Catalog.GetString("Compulsory Settings");
        this.hbox10.Add(this.label10);
        Gtk.Box.BoxChild w37 = ((Gtk.Box.BoxChild)(this.hbox10[this.label10]));
        w37.Position = 1;
        w37.Expand = false;
        w37.Fill = false;
        w37.Padding = ((uint)(6));
        this.vbox6.Add(this.hbox10);
        Gtk.Box.BoxChild w38 = ((Gtk.Box.BoxChild)(this.vbox6[this.hbox10]));
        w38.Position = 0;
        w38.Expand = false;
        w38.Fill = false;
        w38.Padding = ((uint)(6));
        // Container child vbox6.Gtk.Box+BoxChild
        this.hbox19 = new Gtk.HBox();
        this.hbox19.Name = "hbox19";
        this.hbox19.Spacing = 6;
        // Container child hbox19.Gtk.Box+BoxChild
        this.hseparator2 = new Gtk.HSeparator();
        this.hseparator2.Name = "hseparator2";
        this.hbox19.Add(this.hseparator2);
        Gtk.Box.BoxChild w39 = ((Gtk.Box.BoxChild)(this.hbox19[this.hseparator2]));
        w39.Position = 0;
        w39.Padding = ((uint)(6));
        this.vbox6.Add(this.hbox19);
        Gtk.Box.BoxChild w40 = ((Gtk.Box.BoxChild)(this.vbox6[this.hbox19]));
        w40.Position = 1;
        w40.Expand = false;
        w40.Fill = false;
        // Container child vbox6.Gtk.Box+BoxChild
        this.hbox11 = new Gtk.HBox();
        this.hbox11.Name = "hbox11";
        this.hbox11.Spacing = 6;
        // Container child hbox11.Gtk.Box+BoxChild
        this.label5 = new Gtk.Label();
        this.label5.WidthRequest = 150;
        this.label5.Name = "label5";
        this.label5.LabelProp = Mono.Unix.Catalog.GetString("Forum Username");
        this.hbox11.Add(this.label5);
        Gtk.Box.BoxChild w41 = ((Gtk.Box.BoxChild)(this.hbox11[this.label5]));
        w41.Position = 0;
        w41.Expand = false;
        w41.Fill = false;
        w41.Padding = ((uint)(6));
        // Container child hbox11.Gtk.Box+BoxChild
        this.entry1 = new Gtk.Entry();
        this.entry1.CanFocus = true;
        this.entry1.Name = "entry1";
        this.entry1.IsEditable = true;
        this.entry1.WidthChars = 25;
        this.entry1.InvisibleChar = '●';
        this.hbox11.Add(this.entry1);
        Gtk.Box.BoxChild w42 = ((Gtk.Box.BoxChild)(this.hbox11[this.entry1]));
        w42.Position = 2;
        w42.Expand = false;
        w42.Padding = ((uint)(6));
        this.vbox6.Add(this.hbox11);
        Gtk.Box.BoxChild w43 = ((Gtk.Box.BoxChild)(this.vbox6[this.hbox11]));
        w43.Position = 2;
        w43.Expand = false;
        w43.Fill = false;
        // Container child vbox6.Gtk.Box+BoxChild
        this.hbox12 = new Gtk.HBox();
        this.hbox12.Name = "hbox12";
        this.hbox12.Spacing = 6;
        // Container child hbox12.Gtk.Box+BoxChild
        this.label6 = new Gtk.Label();
        this.label6.WidthRequest = 150;
        this.label6.Name = "label6";
        this.label6.LabelProp = Mono.Unix.Catalog.GetString("Forum Password");
        this.hbox12.Add(this.label6);
        Gtk.Box.BoxChild w44 = ((Gtk.Box.BoxChild)(this.hbox12[this.label6]));
        w44.Position = 0;
        w44.Expand = false;
        w44.Fill = false;
        w44.Padding = ((uint)(6));
        // Container child hbox12.Gtk.Box+BoxChild
        this.entry2 = new Gtk.Entry();
        this.entry2.CanFocus = true;
        this.entry2.Name = "entry2";
        this.entry2.IsEditable = true;
        this.entry2.WidthChars = 25;
        this.entry2.InvisibleChar = '●';
        this.hbox12.Add(this.entry2);
        Gtk.Box.BoxChild w45 = ((Gtk.Box.BoxChild)(this.hbox12[this.entry2]));
        w45.Position = 2;
        w45.Expand = false;
        w45.Padding = ((uint)(6));
        this.vbox6.Add(this.hbox12);
        Gtk.Box.BoxChild w46 = ((Gtk.Box.BoxChild)(this.vbox6[this.hbox12]));
        w46.Position = 3;
        w46.Expand = false;
        w46.Fill = false;
        // Container child vbox6.Gtk.Box+BoxChild
        this.hbox13 = new Gtk.HBox();
        this.hbox13.Name = "hbox13";
        this.hbox13.Spacing = 6;
        // Container child hbox13.Gtk.Box+BoxChild
        this.label7 = new Gtk.Label();
        this.label7.WidthRequest = 150;
        this.label7.Name = "label7";
        this.label7.LabelProp = Mono.Unix.Catalog.GetString("Modem Username");
        this.hbox13.Add(this.label7);
        Gtk.Box.BoxChild w47 = ((Gtk.Box.BoxChild)(this.hbox13[this.label7]));
        w47.Position = 0;
        w47.Expand = false;
        w47.Fill = false;
        w47.Padding = ((uint)(6));
        // Container child hbox13.Gtk.Box+BoxChild
        this.entry3 = new Gtk.Entry();
        this.entry3.CanFocus = true;
        this.entry3.Name = "entry3";
        this.entry3.IsEditable = true;
        this.entry3.WidthChars = 25;
        this.entry3.InvisibleChar = '●';
        this.hbox13.Add(this.entry3);
        Gtk.Box.BoxChild w48 = ((Gtk.Box.BoxChild)(this.hbox13[this.entry3]));
        w48.Position = 2;
        w48.Expand = false;
        w48.Padding = ((uint)(6));
        this.vbox6.Add(this.hbox13);
        Gtk.Box.BoxChild w49 = ((Gtk.Box.BoxChild)(this.vbox6[this.hbox13]));
        w49.Position = 4;
        w49.Expand = false;
        w49.Fill = false;
        // Container child vbox6.Gtk.Box+BoxChild
        this.hbox14 = new Gtk.HBox();
        this.hbox14.Name = "hbox14";
        this.hbox14.Spacing = 6;
        // Container child hbox14.Gtk.Box+BoxChild
        this.label8 = new Gtk.Label();
        this.label8.WidthRequest = 150;
        this.label8.Name = "label8";
        this.label8.LabelProp = Mono.Unix.Catalog.GetString("Modem Password");
        this.hbox14.Add(this.label8);
        Gtk.Box.BoxChild w50 = ((Gtk.Box.BoxChild)(this.hbox14[this.label8]));
        w50.Position = 0;
        w50.Expand = false;
        w50.Fill = false;
        w50.Padding = ((uint)(6));
        // Container child hbox14.Gtk.Box+BoxChild
        this.entry4 = new Gtk.Entry();
        this.entry4.CanFocus = true;
        this.entry4.Name = "entry4";
        this.entry4.IsEditable = true;
        this.entry4.WidthChars = 25;
        this.entry4.InvisibleChar = '●';
        this.hbox14.Add(this.entry4);
        Gtk.Box.BoxChild w51 = ((Gtk.Box.BoxChild)(this.hbox14[this.entry4]));
        w51.Position = 2;
        w51.Expand = false;
        w51.Padding = ((uint)(6));
        this.vbox6.Add(this.hbox14);
        Gtk.Box.BoxChild w52 = ((Gtk.Box.BoxChild)(this.vbox6[this.hbox14]));
        w52.Position = 5;
        w52.Expand = false;
        w52.Fill = false;
        // Container child vbox6.Gtk.Box+BoxChild
        this.label30 = new Gtk.Label();
        this.label30.Name = "label30";
        this.label30.LabelProp = Mono.Unix.Catalog.GetString(".");
        this.vbox6.Add(this.label30);
        Gtk.Box.BoxChild w53 = ((Gtk.Box.BoxChild)(this.vbox6[this.label30]));
        w53.Position = 6;
        w53.Expand = false;
        w53.Fill = false;
        w53.Padding = ((uint)(10));
        // Container child vbox6.Gtk.Box+BoxChild
        this.hbox20 = new Gtk.HBox();
        this.hbox20.Name = "hbox20";
        this.hbox20.Spacing = 6;
        // Container child hbox20.Gtk.Box+BoxChild
        this.label11 = new Gtk.Label();
        this.label11.Name = "label11";
        this.label11.LabelProp = Mono.Unix.Catalog.GetString("Other Settings");
        this.hbox20.Add(this.label11);
        Gtk.Box.BoxChild w54 = ((Gtk.Box.BoxChild)(this.hbox20[this.label11]));
        w54.Position = 1;
        w54.Expand = false;
        w54.Fill = false;
        w54.Padding = ((uint)(6));
        this.vbox6.Add(this.hbox20);
        Gtk.Box.BoxChild w55 = ((Gtk.Box.BoxChild)(this.vbox6[this.hbox20]));
        w55.Position = 7;
        w55.Expand = false;
        w55.Fill = false;
        // Container child vbox6.Gtk.Box+BoxChild
        this.hbox18 = new Gtk.HBox();
        this.hbox18.Name = "hbox18";
        this.hbox18.Spacing = 6;
        // Container child hbox18.Gtk.Box+BoxChild
        this.hseparator1 = new Gtk.HSeparator();
        this.hseparator1.Name = "hseparator1";
        this.hbox18.Add(this.hseparator1);
        Gtk.Box.BoxChild w56 = ((Gtk.Box.BoxChild)(this.hbox18[this.hseparator1]));
        w56.Position = 0;
        w56.Padding = ((uint)(6));
        this.vbox6.Add(this.hbox18);
        Gtk.Box.BoxChild w57 = ((Gtk.Box.BoxChild)(this.vbox6[this.hbox18]));
        w57.Position = 8;
        w57.Expand = false;
        w57.Fill = false;
        // Container child vbox6.Gtk.Box+BoxChild
        this.hbox15 = new Gtk.HBox();
        this.hbox15.Name = "hbox15";
        this.hbox15.Spacing = 6;
        // Container child hbox15.Gtk.Box+BoxChild
        this.label9 = new Gtk.Label();
        this.label9.WidthRequest = 150;
        this.label9.Name = "label9";
        this.label9.LabelProp = Mono.Unix.Catalog.GetString("Update Interval");
        this.hbox15.Add(this.label9);
        Gtk.Box.BoxChild w58 = ((Gtk.Box.BoxChild)(this.hbox15[this.label9]));
        w58.Position = 0;
        w58.Expand = false;
        w58.Fill = false;
        w58.Padding = ((uint)(6));
        // Container child hbox15.Gtk.Box+BoxChild
        this.combobox1 = Gtk.ComboBox.NewText();
        this.combobox1.AppendText(Mono.Unix.Catalog.GetString("3 hours"));
        this.combobox1.AppendText(Mono.Unix.Catalog.GetString("6 hours"));
        this.combobox1.AppendText(Mono.Unix.Catalog.GetString("12 hours"));
        this.combobox1.AppendText(Mono.Unix.Catalog.GetString("Daily"));
        this.combobox1.AppendText(Mono.Unix.Catalog.GetString("Weekly"));
        this.combobox1.WidthRequest = 150;
        this.combobox1.Name = "combobox1";
        this.combobox1.Active = 0;
        this.hbox15.Add(this.combobox1);
        Gtk.Box.BoxChild w59 = ((Gtk.Box.BoxChild)(this.hbox15[this.combobox1]));
        w59.Position = 2;
        w59.Expand = false;
        w59.Fill = false;
        w59.Padding = ((uint)(6));
        this.vbox6.Add(this.hbox15);
        Gtk.Box.BoxChild w60 = ((Gtk.Box.BoxChild)(this.vbox6[this.hbox15]));
        w60.Position = 9;
        w60.Expand = false;
        w60.Fill = false;
        // Container child vbox6.Gtk.Box+BoxChild
        this.hbox16 = new Gtk.HBox();
        this.hbox16.Name = "hbox16";
        this.hbox16.Spacing = 6;
        // Container child hbox16.Gtk.Box+BoxChild
        this.label12 = new Gtk.Label();
        this.label12.WidthRequest = 150;
        this.label12.Name = "label12";
        this.label12.LabelProp = Mono.Unix.Catalog.GetString("Line Cap");
        this.hbox16.Add(this.label12);
        Gtk.Box.BoxChild w61 = ((Gtk.Box.BoxChild)(this.hbox16[this.label12]));
        w61.Position = 0;
        w61.Expand = false;
        w61.Fill = false;
        w61.Padding = ((uint)(6));
        // Container child hbox16.Gtk.Box+BoxChild
        this.combobox4 = Gtk.ComboBox.NewText();
        this.combobox4.AppendText(Mono.Unix.Catalog.GetString("5 gb"));
        this.combobox4.AppendText(Mono.Unix.Catalog.GetString("10 gb"));
        this.combobox4.AppendText(Mono.Unix.Catalog.GetString("15 gb"));
        this.combobox4.AppendText(Mono.Unix.Catalog.GetString("20 gb"));
        this.combobox4.AppendText(Mono.Unix.Catalog.GetString("25 gb"));
        this.combobox4.AppendText(Mono.Unix.Catalog.GetString("30 gb"));
        this.combobox4.AppendText(Mono.Unix.Catalog.GetString("35 gb"));
        this.combobox4.AppendText(Mono.Unix.Catalog.GetString("40 gb"));
        this.combobox4.AppendText(Mono.Unix.Catalog.GetString("45 gb"));
        this.combobox4.AppendText(Mono.Unix.Catalog.GetString("50 gb"));
        this.combobox4.AppendText(Mono.Unix.Catalog.GetString("55 gb"));
        this.combobox4.AppendText(Mono.Unix.Catalog.GetString("60 gb"));
        this.combobox4.AppendText(Mono.Unix.Catalog.GetString("65 gb"));
        this.combobox4.AppendText(Mono.Unix.Catalog.GetString("70 gb"));
        this.combobox4.AppendText(Mono.Unix.Catalog.GetString("75 gb"));
        this.combobox4.AppendText(Mono.Unix.Catalog.GetString("80 gb"));
        this.combobox4.AppendText(Mono.Unix.Catalog.GetString("85 gb"));
        this.combobox4.AppendText(Mono.Unix.Catalog.GetString("90 gb"));
        this.combobox4.AppendText(Mono.Unix.Catalog.GetString("95 gb"));
        this.combobox4.AppendText(Mono.Unix.Catalog.GetString("100 gb"));
        this.combobox4.AppendText(Mono.Unix.Catalog.GetString("110 gb"));
        this.combobox4.AppendText(Mono.Unix.Catalog.GetString("120 gb"));
        this.combobox4.AppendText(Mono.Unix.Catalog.GetString("130 gb"));
        this.combobox4.AppendText(Mono.Unix.Catalog.GetString("140 gb"));
        this.combobox4.AppendText(Mono.Unix.Catalog.GetString("150 gb"));
        this.combobox4.AppendText(Mono.Unix.Catalog.GetString("160 gb"));
        this.combobox4.AppendText(Mono.Unix.Catalog.GetString("170 gb"));
        this.combobox4.AppendText(Mono.Unix.Catalog.GetString("180 gb"));
        this.combobox4.AppendText(Mono.Unix.Catalog.GetString("190 gb"));
        this.combobox4.AppendText(Mono.Unix.Catalog.GetString("200 gb"));
        this.combobox4.WidthRequest = 150;
        this.combobox4.Name = "combobox4";
        this.combobox4.Active = 26;
        this.hbox16.Add(this.combobox4);
        Gtk.Box.BoxChild w62 = ((Gtk.Box.BoxChild)(this.hbox16[this.combobox4]));
        w62.Position = 2;
        w62.Expand = false;
        w62.Fill = false;
        w62.Padding = ((uint)(6));
        this.vbox6.Add(this.hbox16);
        Gtk.Box.BoxChild w63 = ((Gtk.Box.BoxChild)(this.vbox6[this.hbox16]));
        w63.Position = 10;
        w63.Expand = false;
        w63.Fill = false;
        // Container child vbox6.Gtk.Box+BoxChild
        this.hbox17 = new Gtk.HBox();
        this.hbox17.Name = "hbox17";
        this.hbox17.Spacing = 6;
        // Container child hbox17.Gtk.Box+BoxChild
        this.label13 = new Gtk.Label();
        this.label13.WidthRequest = 150;
        this.label13.Name = "label13";
        this.label13.LabelProp = Mono.Unix.Catalog.GetString("Critical Notification");
        this.hbox17.Add(this.label13);
        Gtk.Box.BoxChild w64 = ((Gtk.Box.BoxChild)(this.hbox17[this.label13]));
        w64.Position = 0;
        w64.Expand = false;
        w64.Fill = false;
        w64.Padding = ((uint)(6));
        // Container child hbox17.Gtk.Box+BoxChild
        this.combobox3 = Gtk.ComboBox.NewText();
        this.combobox3.AppendText(Mono.Unix.Catalog.GetString("5 gb"));
        this.combobox3.AppendText(Mono.Unix.Catalog.GetString("10 gb"));
        this.combobox3.AppendText(Mono.Unix.Catalog.GetString("15 gb"));
        this.combobox3.AppendText(Mono.Unix.Catalog.GetString("20 gb"));
        this.combobox3.AppendText(Mono.Unix.Catalog.GetString("25 gb"));
        this.combobox3.AppendText(Mono.Unix.Catalog.GetString("30 gb"));
        this.combobox3.AppendText(Mono.Unix.Catalog.GetString("35 gb"));
        this.combobox3.AppendText(Mono.Unix.Catalog.GetString("40 gb"));
        this.combobox3.AppendText(Mono.Unix.Catalog.GetString("45 gb"));
        this.combobox3.AppendText(Mono.Unix.Catalog.GetString("50 gb"));
        this.combobox3.AppendText(Mono.Unix.Catalog.GetString("55 gb"));
        this.combobox3.AppendText(Mono.Unix.Catalog.GetString("60 gb"));
        this.combobox3.AppendText(Mono.Unix.Catalog.GetString("65 gb"));
        this.combobox3.AppendText(Mono.Unix.Catalog.GetString("70 gb"));
        this.combobox3.AppendText(Mono.Unix.Catalog.GetString("75 gb"));
        this.combobox3.AppendText(Mono.Unix.Catalog.GetString("80 gb"));
        this.combobox3.AppendText(Mono.Unix.Catalog.GetString("85 gb"));
        this.combobox3.AppendText(Mono.Unix.Catalog.GetString("90 gb"));
        this.combobox3.AppendText(Mono.Unix.Catalog.GetString("95 gb"));
        this.combobox3.AppendText(Mono.Unix.Catalog.GetString("100 gb"));
        this.combobox3.AppendText(Mono.Unix.Catalog.GetString("110 gb"));
        this.combobox3.AppendText(Mono.Unix.Catalog.GetString("120 gb"));
        this.combobox3.AppendText(Mono.Unix.Catalog.GetString("130 gb"));
        this.combobox3.AppendText(Mono.Unix.Catalog.GetString("140 gb"));
        this.combobox3.AppendText(Mono.Unix.Catalog.GetString("150 gb"));
        this.combobox3.AppendText(Mono.Unix.Catalog.GetString("160 gb"));
        this.combobox3.AppendText(Mono.Unix.Catalog.GetString("170 gb"));
        this.combobox3.AppendText(Mono.Unix.Catalog.GetString("180 gb"));
        this.combobox3.AppendText(Mono.Unix.Catalog.GetString("190 gb"));
        this.combobox3.AppendText(Mono.Unix.Catalog.GetString("200 gb"));
        this.combobox3.WidthRequest = 150;
        this.combobox3.Name = "combobox3";
        this.combobox3.Active = 24;
        this.hbox17.Add(this.combobox3);
        Gtk.Box.BoxChild w65 = ((Gtk.Box.BoxChild)(this.hbox17[this.combobox3]));
        w65.Position = 2;
        w65.Expand = false;
        w65.Fill = false;
        w65.Padding = ((uint)(6));
        this.vbox6.Add(this.hbox17);
        Gtk.Box.BoxChild w66 = ((Gtk.Box.BoxChild)(this.vbox6[this.hbox17]));
        w66.Position = 11;
        w66.Expand = false;
        w66.Fill = false;
        // Container child vbox6.Gtk.Box+BoxChild
        this.hbox23 = new Gtk.HBox();
        this.hbox23.Name = "hbox23";
        this.hbox23.Spacing = 6;
        // Container child hbox23.Gtk.Box+BoxChild
        this.hseparator5 = new Gtk.HSeparator();
        this.hseparator5.Name = "hseparator5";
        this.hbox23.Add(this.hseparator5);
        Gtk.Box.BoxChild w67 = ((Gtk.Box.BoxChild)(this.hbox23[this.hseparator5]));
        w67.Position = 0;
        w67.Padding = ((uint)(6));
        this.vbox6.Add(this.hbox23);
        Gtk.Box.BoxChild w68 = ((Gtk.Box.BoxChild)(this.vbox6[this.hbox23]));
        w68.Position = 12;
        w68.Expand = false;
        w68.Fill = false;
        w68.Padding = ((uint)(6));
        // Container child vbox6.Gtk.Box+BoxChild
        this.hbox24 = new Gtk.HBox();
        this.hbox24.Name = "hbox24";
        this.hbox24.Spacing = 6;
        // Container child hbox24.Gtk.Box+BoxChild
        this.button1 = new Gtk.Button();
        this.button1.WidthRequest = 80;
        this.button1.CanFocus = true;
        this.button1.Name = "button1";
        this.button1.UseUnderline = true;
        this.button1.Label = Mono.Unix.Catalog.GetString("Save");
        this.hbox24.Add(this.button1);
        Gtk.Box.BoxChild w69 = ((Gtk.Box.BoxChild)(this.hbox24[this.button1]));
        w69.Position = 0;
        w69.Expand = false;
        w69.Fill = false;
        w69.Padding = ((uint)(20));
        this.vbox6.Add(this.hbox24);
        Gtk.Box.BoxChild w70 = ((Gtk.Box.BoxChild)(this.vbox6[this.hbox24]));
        w70.Position = 13;
        w70.Expand = false;
        w70.Fill = false;
        w70.Padding = ((uint)(6));
        this.notebook1.Add(this.vbox6);
        Gtk.Notebook.NotebookChild w71 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox6]));
        w71.Position = 3;
        // Notebook tab
        this.label4 = new Gtk.Label();
        this.label4.Name = "label4";
        this.label4.LabelProp = Mono.Unix.Catalog.GetString("Setup");
        this.notebook1.SetTabLabel(this.vbox6, this.label4);
        this.label4.ShowAll();
        this.hbox4.Add(this.notebook1);
        Gtk.Box.BoxChild w72 = ((Gtk.Box.BoxChild)(this.hbox4[this.notebook1]));
        w72.Position = 1;
        w72.Padding = ((uint)(6));
        this.vbox2.Add(this.hbox4);
        Gtk.Box.BoxChild w73 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox4]));
        w73.Position = 1;
        // Container child vbox2.Gtk.Box+BoxChild
        this.statusbar1 = new Gtk.Statusbar();
        this.statusbar1.Name = "statusbar1";
        this.statusbar1.Spacing = 6;
        this.vbox2.Add(this.statusbar1);
        Gtk.Box.BoxChild w74 = ((Gtk.Box.BoxChild)(this.vbox2[this.statusbar1]));
        w74.Position = 2;
        w74.Expand = false;
        w74.Fill = false;
        this.Add(this.vbox2);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 616;
        this.DefaultHeight = 484;
        this.Hide();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.DestroyEvent += new Gtk.DestroyEventHandler(this.OnDestroyEvent);
        this.exitAction.Activated += new System.EventHandler(this.OnExitActionActivated);
        this.button1.Clicked += new System.EventHandler(this.OnButton1Clicked);
    }
}
